
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uleqzlzlpmhqiefdbriz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsZXF6bHpscG1ocWllZmRicml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3ODE0OTksImV4cCI6MjA1OTM1NzQ5OX0.ix9eO-69npi1zzL-4g5IIq0y943chNVRLDpMYE6fAuo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
