
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uleqzlzlpmhqiefdbriz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsZXF6bHpscG1ocWllZmRicml6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3ODE0OTksImV4cCI6MjA1OTM1NzQ5OX0.ix9eO-69npi1zzL-4g5IIq0y943chNVRLDpMYE6fAuo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Enable Supabase Realtime functionality for learning_content table
const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  realtime: {
    params: {
      eventsPerSecond: 10,
    },
  },
});

// Run this statement to enable realtime on all tables
(async () => {
  // Enable realtime for specific tables
  await supabase.channel('custom-all-channel')
    .on('postgres_changes', { event: '*', schema: 'public', table: 'messages' }, payload => {
      console.log('Change received!', payload);
    })
    .on('postgres_changes', { event: '*', schema: 'public', table: 'learning_content' }, payload => {
      console.log('Learning content changed:', payload);
    })
    .on('postgres_changes', { event: '*', schema: 'public', table: 'profiles' }, payload => {
      console.log('Profiles changed:', payload);
    })
    .subscribe();
})();

export { supabase };
